package com.newchar.supportlibrary.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.newchar.supportlibrary.db.entry.LoginRecord;

import com.newchar.supportlibrary.db.dao.LoginRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginRecordDaoConfig;

    private final LoginRecordDao loginRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginRecordDaoConfig = daoConfigMap.get(LoginRecordDao.class).clone();
        loginRecordDaoConfig.initIdentityScope(type);

        loginRecordDao = new LoginRecordDao(loginRecordDaoConfig, this);

        registerDao(LoginRecord.class, loginRecordDao);
    }
    
    public void clear() {
        loginRecordDaoConfig.clearIdentityScope();
    }

    public LoginRecordDao getLoginRecordDao() {
        return loginRecordDao;
    }

}
